## 运算

* 相同大小 Tensor 之间的任何算术运算都会将运算应用到元素级
* 不同大小 Tensor(要求dimension 0 必须相同) 之间的运算叫做广播(broadcasting)
* Tensor 与 Scalar(0维 tensor) 间的算术运算会将那个标量值传播到各个元素
* Note： TensorFLow 在进行数学运算时，一定要求各个 Tensor 数据类型一致

In [1]:
import tensorflow as tf
import numpy as np

### tf.sign和tf.reduce_sum

* tf.reduce_sum(input_tensor,reduction_indices = None,keep_dims = False,name = None) 降维相加
* tf.sign(x,name = None)返回x的符号 

In [26]:
x = [[1,0,2],[-1,2,4],[5,-5,0],[0,5,4]]
x = np.array(x)
A = tf.sign(x)
B = tf.reduce_sum(A,reduction_indices=1)

In [27]:
print('Ashape',A.shape)
print('Bshape',B.shape)

Ashape (4, 3)
Bshape (4,)


In [28]:
with tf.Session() as sess:
    print(sess.run(A))
    print(sess.run(B))
    print('Ashape',A.shape)
    print('Bshape',B.shape)

[[ 1  0  1]
 [-1  1  1]
 [ 1 -1  0]
 [ 0  1  1]]
[2 1 0 2]
Ashape (4, 3)
Bshape (4,)


In [29]:
A = tf.sign(x)
B = tf.reduce_sum(A,reduction_indices=0)
with tf.Session() as sess:
    print(sess.run(A))
    print(sess.run(B))
    print('Ashape',A.shape)
    print('Bshape',B.shape)

[[ 1  0  1]
 [-1  1  1]
 [ 1 -1  0]
 [ 0  1  1]]
[1 1 3]
Ashape (4, 3)
Bshape (3,)


In [30]:
A = tf.sign(x)
B = tf.reduce_sum(A,reduction_indices=[0,1])
with tf.Session() as sess:
    print(sess.run(A))
    print(sess.run(B))
    print('Ashape',A.shape)
    print('Bshape',B.shape)

[[ 1  0  1]
 [-1  1  1]
 [ 1 -1  0]
 [ 0  1  1]]
5
Ashape (4, 3)
Bshape ()


##### 分析
* resuce_sum可以对矩阵的某一，或者某几维度进行相加
* 其中 可以认为 reduction_indices的输入维度是几，对应输出矩阵的该位置的维度就会降维0
    如：shape = （4,3）的矩阵 reduce_sum with reduction_indices = 1 输出矩阵维度为 (4,)

In [31]:
x = [[[1,0,2],[-1,2,4]],[[5,-5,0],[0,5,4]]]
x = np.array(x)
A = tf.sign(x)
B = tf.reduce_sum(A,reduction_indices=1)

print('Ashape',A.shape)
print('Bshape',B.shape)

Ashape (2, 2, 3)
Bshape (2, 3)


In [32]:
with tf.Session() as sess:
    print(sess.run(A))
    print(sess.run(B))

[[[ 1  0  1]
  [-1  1  1]]

 [[ 1 -1  0]
  [ 0  1  1]]]
[[0 1 2]
 [1 0 1]]


### + - × /
* 分别对应 add subtract multiply divide(div,div支持不同维度的除法)
* 同样支持符号直接运算

In [55]:
x = [[3,2],[-1,5]]
x = tf.Variable(x,name = 'x')
x_sign = tf.sign(x)
print(x)

<tf.Variable 'x_5:0' shape=(2, 2) dtype=int32_ref>


In [56]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    y = x + x_sign
    sess.run(y)
    print('y',y.eval(),'\n')
    
    y = x - x_sign
    sess.run(y)
    print('y',y.eval(),'\n')
    
    y = x * x_sign
    sess.run(y)
    print('y',y.eval(),'\n')
    
    y = x_sign/x
    sess.run(y)
    print('y',y.eval(),'\n')
    
    x = tf.reduce_sum(x,0)
    print('x',x.eval(),'\n')
    y = tf.div(x_sign,x) 
    sess.run(y)
    print('y',y.eval())

y [[ 4  3]
 [-2  6]] 

y [[2 1]
 [0 4]] 

y [[3 2]
 [1 5]] 

y [[ 0.33333333  0.5       ]
 [ 1.          0.2       ]] 

x [2 7] 

y [[ 0  0]
 [-1  0]]


#### 其他运算表

##### 算术操作符：+ - * / % 
    tf.add(x, y, name=None)        # 加法(支持 broadcasting)
    tf.subtract(x, y, name=None)   # 减法
    tf.multiply(x, y, name=None)   # 乘法
    tf.divide(x, y, name=None)     # 浮点除法, 返回浮点数(python3 除法)
    tf.mod(x, y, name=None)        # 取余


    ##### 幂指对数操作符：^ ^2 ^0.5 e^ ln 
    tf.pow(x, y, name=None)        # 幂次方
    tf.square(x, name=None)        # 平方
    tf.sqrt(x, name=None)          # 开根号，必须传入浮点数或复数
    tf.exp(x, name=None)           # 计算 e 的次方
    tf.log(x, name=None)           # 以 e 为底，必须传入浮点数或复数


    ##### 取符号、负、倒数、绝对值、近似、两数中较大/小的
    tf.negative(x, name=None)      # 取负(y = -x).
    tf.sign(x, name=None)          # 返回 x 的符号
    tf.reciprocal(x, name=None)    # 取倒数
    tf.abs(x, name=None)           # 求绝对值
    tf.round(x, name=None)         # 四舍五入
    tf.ceil(x, name=None)          # 向上取整
    tf.floor(x, name=None)         # 向下取整
    tf.rint(x, name=None)          # 取最接近的整数 
    tf.maximum(x, y, name=None)    # 返回两tensor中的最大值 (x > y ? x : y)
    tf.minimum(x, y, name=None)    # 返回两tensor中的最小值 (x < y ? x : y)


    ##### 三角函数和反三角函数
    tf.cos(x, name=None)    
    tf.sin(x, name=None)    
    tf.tan(x, name=None)    
    tf.acos(x, name=None)
    tf.asin(x, name=None)
    tf.atan(x, name=None)   


    ##### 其它
    tf.div(x, y, name=None)  # python 2.7 除法, x/y-->int or x/float(y)-->float
    tf.truediv(x, y, name=None) # python 3 除法, x/y-->float
    tf.floordiv(x, y, name=None)  # python 3 除法, x//y-->int
    tf.realdiv(x, y, name=None)
    tf.truncatediv(x, y, name=None)
    tf.floor_div(x, y, name=None)
    tf.truncatemod(x, y, name=None)
    tf.floormod(x, y, name=None)
    tf.cross(x, y, name=None)
    tf.add_n(inputs, name=None)  # inputs: A list of Tensor objects, each with same shape and type
    tf.squared_difference(x, y, name=None) 

### 矩阵运算

### 转置，可以通过指定 perm=[1, 0] 来进行轴变换
tf.transpose(a, perm=None, name='transpose')

In [65]:
x = [[1,2],[3,4]]
y = tf.matrix_transpose(x, name='matrix_transpose')
with tf.Session() as sess:
    sess.run(y)
    print(y.eval())

[[1 3]
 [2 4]]


#### 其他主要运算

    # 矩阵乘法(tensors of rank >= 2)
    tf.matmul(a, b, transpose_a=False, transpose_b=False,    adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)


    # 求矩阵的迹
    tf.trace(x, name=None)


    # 计算方阵行列式的值
    tf.matrix_determinant(input, name=None)


    # 求解可逆方阵的逆，input 必须为浮点型或复数
    tf.matrix_inverse(input, adjoint=None, name=None)


    # 奇异值分解
    tf.svd(tensor, full_matrices=False, compute_uv=True, name=None)


    # QR 分解
    tf.qr(input, full_matrices=None, name=None)


    # 求张量的范数(默认2)
    tf.norm(tensor, ord='euclidean', axis=None, keep_dims=False, name=None)



    # 构建一个单位矩阵, 或者 batch 个矩阵，batch_shape 以 list 的形式传入
    tf.eye(num_rows, num_columns=None, batch_shape=None, dtype=tf.float32, name=None)
    # Construct one identity matrix.
    tf.eye(2)
    ==> [[1., 0.],
         [0., 1.]]

    # Construct a batch of 3 identity matricies, each 2 x 2.
    # batch_identity[i, :, :] is a 2 x 2 identity matrix, i = 0, 1, 2.
    batch_identity = tf.eye(2, batch_shape=[3])

    # Construct one 2 x 3 "identity" matrix
    tf.eye(2, num_columns=3)
    ==> [[ 1.,  0.,  0.],
         [ 0.,  1.,  0.]]


    # 构建一个对角矩阵，rank = 2*rank(diagonal)
    tf.diag(diagonal, name=None)
    # 'diagonal' is [1, 2, 3, 4]
    tf.diag(diagonal) ==> [[1, 0, 0, 0]
                           [0, 2, 0, 0]
                           [0, 0, 3, 0]
                           [0, 0, 0, 4]]



    # 其它
    tf.diag_part
    tf.matrix_diag
    tf.matrix_diag_part
    tf.matrix_band_part
    tf.matrix_set_diag
    tf.cholesky
    tf.cholesky_solve
    tf.matrix_solve
    tf.matrix_triangular_solve
    tf.matrix_solve_ls
    tf.self_adjoint_eig
    tf.self_adjoint_eigvals